### ISSUE TITLE
lineage calls failing from pair-end fastq files

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#100]
only use the _R1.fastq file, no need to input both to the script (I think it may fail if you do that).

**Comment by doctormo** [comment]
Can you link to the failing pipeline? I can't see lineage being used in any pair-end fastq pipelines yet.

**Comment by mahafarhat** [comment]
let's please include the lineage piece in the pair-end WGS pipeline

**Comment by doctormo** [comment]
This is now solved. Pair-end now uses the R1 fastq file in it's lineage call in the WGS pipeline.
