### ISSUE TITLE
Predict file name inputs are too strict

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#102]
Can we modify the pipeline to treat the following as equivalent alternative names

1) .fastq = .fq
2) _R1.fastq = _1.fastq = .1.fastq
3) _R2.fastq = _2.fastq = .2.fastq
4) .fastq.gz = .fq.gz

some users are having trouble, and it's a pain to rename all of their files once in dropbox

**Comment by doctormo** [comment]
This is now fixed as it allows many varients based on regular expressions.
