### ISSUE TITLE
Generate mutation count per gene scatter plots interactively from the heatmap

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#11]
Here are detailed instructions on this. I included example html files in the apps/predict folder under a subfolder html (as I couldn't attach html files here)

[TBpredict_output.pdf](https://github.com/IQSS/gentb-site/files/174267/TBpredict_output.pdf)

**Comment by mahafarhat** [comment]
I'm working on some changes to the predict pipeline to allow it to output both the heatmap and the scatter plots (the latter are not integrated into the pipeline yet). There will be one heatmap per json file, but many possible scatter plots per json file and their number = 13 (number of drugs) x the number of strains (that the user inputs)    and corresponding to the number of squares in the heatmap.

I can think of two possible ways of generating these interactively from the heatmap, please let me know if you think one is better so I can work accordingly:
 
1) the user clicks on a box in the heatmap that corresponds to a (drug, strainid) set, this is fed to a new R script that generates the scatterplot with the drug, strainid input and the matrix.json input, and then this is displayed

2) All the possible combinations of scatterplots are generated automatically through a new function that I can add to the TBpredict.R script and stored in the output folder and labeled with the drug and strainid names. The user clicks on a box in the heatmap that corresponds to a (drug, strainid) set, the appropriate scatterplot html file is fetched and displayed

**Comment by mahafarhat** [comment]
I added an R folder under apps that has some example files and my working version of charts-V4.R that generates scatterplots. I will clear this up further when we resolve the issues Martin is having with the TBpredict.R script

**Comment by doctormo** [comment]
This is now complete (will be deployed soon)
