### ISSUE TITLE
updates to/reformating of predict output page

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#16]
1- remove title field
2- display status only if processing was NOT successful
3- move desc, file type, filenames to the top above the graphical result display
4- move y axis of heatmap to the left hand side
5- rename heatmap to "resistance prediction results"
6- add ? symbol that displays the following text when hovered over:
"Colors more towards the red spectrum represent a higher probability of resistance, colors more blue represent less evidence for resistance. Please note that some error is expected in these predicted probabilities. Hovering over each box corresponding to each strain/drug combination displays the predicted probability of resistance as well as the false positive resistance rate ( resistance probability being falsely >50%), and the false negative resistance rate (resistance probability being falsely <50%). Clicking on each box displays a plot of the mutations contributing to resistance prediction (see minimal list of predictive mutations Farhat et al. AJRCCM 2016)"
7- Display strain/drug title for scatter plot or highlight the clicked box in the heatmap.

**Comment by doctormo** [comment]
The long hover text creates a problem, please review the screenshot attached.
![screenshot from 2016-04-28 13-07-41](https://cloud.githubusercontent.com/assets/589384/14894570/43613486-0d42-11e6-8140-e4176a4145d2.png)

**Comment by doctormo** [comment]
All other issues are complete.

**Comment by mahafarhat** [comment]
To resolve the long hover issue please add an additional "info" icon by the ? icon: please split the text as follows:
? icon: "More red represents a higher probability of resistance. More blue represent less evidence for resistance. Hovering over each box displays the predicted probability of resistance, false positive resistance rate and the false negative resistance rate. Clicking on each box displays a plot of the mutations contributing to resistance prediction."
info icon: "See minimal list of predictive mutations in Farhat et al. AJRCCM 2016"

**Comment by doctormo** [comment]
Complete
