### ISSUE TITLE
Updates to genTB site text

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#17]
Please make the following changes:

1- 
in the <About> page, and under the heading <Random Forest Classifer> please change the following sentence:
"Development and validation of this Prediction classifier is described in detail in Farhat MR, Razvan S et. al. under review."
to 
"Development and validation of this Prediction classifier is described in detail in Farhat MR, Razvan S et. al. Genetic Determinants of Drug Resistance in Mycobacterium tuberculosis and Their Diagnostic Value. AJRCCM 2016"

Embedding the following link in "Farhat MR .... 2016":  http://www.ncbi.nlm.nih.gov/pubmed/26910495

2- Please remove "Finally" from the beginning of the paragraph under explore

3- in the <Predict> page please change the following text:
"Minimal genotypic information for accurate resistance predictions are below. Genetic regions are listed in order of decreasing importance. For more detailed list of genetic variants see reference Farhat MR, Sultana R et al. under review"

to 
"Minimal genotypic information for accurate resistance predictions are below. Genetic regions are listed in order of decreasing importance. For more detailed list of genetic variants see reference Farhat MR, Sultana R et al. Genetic Determinants of Drug Resistance in Mycobacterium tuberculosis and Their Diagnostic Value. AJRCCM 2016"

Embedding the following link in "Farhat MR .... 2016":  http://www.ncbi.nlm.nih.gov/pubmed/26910495

**Comment by doctormo** [comment]
Complete.
