### ISSUE TITLE
contact information

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#18]
We seem to have lost the contact information:

I can't exactly what we had there but it should say my name and at least an email address tbpredict@gmail.com

**Comment by doctormo** [comment]
Fixed in the template. Just to make sure I've fixed the right thing, this is the contact link at the bottom of all pages?

**Comment by mahafarhat** [comment]
This shouldn't just say Maha Farhat, MD. But instead should say Maha Farhat, MD MSc tbpredict@gmail.com

**Comment by doctormo** [comment]
So the email address shouldn't be a link, but actually shown on the page?

**Comment by mahafarhat** [comment]
yes on the about page and under contact on the landing page it should be
shown. (This is in addition to embedding it in the contact link at the
bottom near Terms of Use.

**Comment by doctormo** [comment]
Complete
