### ISSUE TITLE
Possible Deployment Improvements

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#2]
The gentb website currently has settings for live and a couple of other setup warts. This issue tracks those issues and their resolution.

**Comment by doctormo** [comment]
- [ ] tb_website/tb_website directory stammer
- [ ] Live settings committed to public repository
- [ ] Settings for live in secret json file and loaded in after
- [ ] Make sure git ignore is sensisible and ignores secret settings files
- [ ] Turn cron-scripts calls into django internal management commands
- [ ] Remove as many full paths as possible in deployment
- [ ] Local pipeline tested as working (without dropbox?)
- [ ] Make convenience manage shell script

**Comment by mahafarhat** [comment]
Great Martin should I assign this issue to you for now? let's discuss at the next meeting

**Comment by doctormo** [comment]
Now redeployed with cleaned up configurations.
