### ISSUE TITLE
Push Privileges 

### ISSUE THREAD

**Issue by jimmyroyer** [IQSS/gentb-site#20]
Hello, I work with Maha on the predictive modeling tools. I'm putting together Neural Network predictive codes in python and I'd like to push my codes in the repository. Is it something that I can be allowed to? Thanks a lot.

**Comment by doctormo** [comment]
Hi Jim, I'll need confirmation from Maha before I can grant access to anything. Let me attach this bug to maha so she can give the nod.

**Comment by jimmyroyer** [comment]
Perfect Martin. Thanks for you help.

**Comment by mahafarhat** [comment]
Hi Martin yes please go ahead. Jimmy is a collaborator working on the predictive modeling piece. He will work within the "R" folder, he wrote some new Python code for prediction that we can test in the future as an alternative to the random forest R code (TBpredict.R).

Best
Maha

**Comment by doctormo** [comment]
Thanks Maha,

And this is great news, I look forward to seeing python random forest, I looked into it briefly and it was complex :+1:

**Comment by doctormo** [comment]
@jimmyroyer - You should have push access, if you are having trouble, let me know what kind of error you have.

**Comment by jimmyroyer** [comment]
Thank you Martin. I get the following error when I try to push my codes:

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags
origin master:master
Pushing to https://github.com/IQSS/gentb-site.git

remote: Permission to IQSS/gentb-site.git denied to jimmyroyer.
fatal: unable to access 'https://github.com/IQSS/gentb-site.git/': The
requested URL returned error: 403


Completed with errors, see above.

**Comment by doctormo** [comment]
@jimmyroyer It looks like your remote is set to http, you should be using ssh (make sure your public key is set in your github settings) and set the remote to the ssh address and try again.

**Comment by jimmyroyer** [comment]
Thank you Martin. I switched to ssh (my public key is in my github account)
and I still get the following error

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags
origin master:master
Pushing to git@github.com:IQSS/gentb-site.git

ERROR: Permission to IQSS/gentb-site.git denied to jimmyroyer.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.




Completed with errors, see above.

**Comment by doctormo** [comment]
OK try now. (fiddled with settings)

**Comment by jimmyroyer** [comment]
it works ! Thanks
