### ISSUE TITLE
Predict page proposal

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#21]
Maha, attached is a screenshot for the predict page.

It shows a buttons per row with a right hand side description, when the button is clicked to takes the user tot he specific form for that type of data entry. If it's a single fastq or  vcf then it's one file from dropbox, if it's pair fastq then it's two dropbox files and the manual is our new drop downs. (all pages would have the name and description fields first)

This should give us the space to describe to the user what each thing is and help them to the right option they need.

What do you think of this layout?
![screenshot from 2016-05-22 16-51-53](https://cloud.githubusercontent.com/assets/589384/15456436/ebe2a5dc-203d-11e6-95b0-a719ba7fd459.png)

**Comment by mahafarhat** [comment]
yes this looks excellent. I have time this friday to speak so we can catch
up. How about 10:00AM?
best
Maha
