### ISSUE TITLE
x-axis of mutation scatter plot in predict output

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#23]
need to make sure x-axis changes for each drug, only plotting the relevant genes for each drug.
[TBpredict_output.pdf](https://github.com/IQSS/gentb-site/files/320689/TBpredict_output.pdf)

)

**Comment by doctormo** [comment]
I've tied the heatmap's generated scatter plot columns to the mutations app, which records the drugs and their gene locusts. Changes to the database will change the scatterplot columns so we can decide to add items later if needed.
