### ISSUE TITLE
Benchmarking files

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#27]
Some standard fastq and vcf files are needed in order to conduct benchmarking research on the code.

**Comment by mahafarhat** [comment]
These are too large to put on the project repository. I can put them in the elsewhere in the cluster. Where is the best place to put them?

**Comment by doctormo** [comment]
The best location for all datafile is on dropbox. That was they can be pulled in directly using the dropbox code.

**Comment by mahafarhat** [comment]
I'm uploading test files into a drop box account, I will send you login information via email.
