### ISSUE TITLE
updates to website txt

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#28]
Maha needs to update these, likely most efficient if Maha can edit the text in the html code directly. Please teach her how and where to look

**Comment by doctormo** [comment]
Education has been provided in person.

**Comment by mahafarhat** [comment]
reassigning this to me so I don't forget to do it

**Comment by mahafarhat** [comment]
change the website citation

**Comment by mahafarhat** [comment]
also add back the document on essential gene regions

**Comment by doctormo** [comment]
Is this bug fixed? (6 months old)

**Comment by mahafarhat** [comment]
I can't seem to find the predict page template files. Where are these in the repository? the ones with "create a prediction from ..."

And just because I likely won't do this correctly can you move the following text from the single end fastq to pair end fastq prediction page:

Please label paired end FastQ files as follows:

    isolate-name-here_R1.fastq
    isolate-name-here_R2.fastq

Replace “isolate-name-here” with your desired isolate or strain name.
