### ISSUE TITLE
Update frequency "My datasets" page

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#32]
Ideally we should have this be updated frequently, or at least that results be pushed immediately to the sites when available. Processing a VCF should take only a few minutes, but 20minutes later the status is still "Dataset CONFIRMED for Dropbox file retrieval "

**Comment by doctormo** [comment]
The pipeline was overheated as it wasn't using bsub (it wasn't installed on the webserver `rc-app-shared01`). It's still not available on the webserver, so we may have to find another way of running the processes.

**Comment by mahafarhat** [comment]
please contact orchestra support about this

**Comment by doctormo** [comment]
Confirmed previous support ticket, this was actually fixed. Sorry for the noise.
