### ISSUE TITLE
Option to receive email when job is successfully completed

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#33]
We need to make sure we implement this if we haven't already

**Comment by doctormo** [comment]
This is already implemented, I've tested it locally to confirm it's attempting to send emails. We can test live email sending.

Does this issue refer to users having the option or not? Some sort of profile settings?

**Comment by mahafarhat** [comment]
it fine if the default is to send an email with no option, because of the time some of these jobs take email is the only consistent means of informing the user of completion of the job.
