### ISSUE TITLE
Predict Job delays and need to maintain a record of processing times

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#34]
It seems that jobs are taking too long to run: this could be 1 of at least 3 reasons:

1- issues/delays with dispatching jobs immediately after data upload
2- jobs are not running 
3- results are available but site is not updated

We have to document the timing of each of these steps at least as we develop this (no need to share with user).

**Comment by doctormo** [comment]
I've added an admin column so we can see how long scripts are taking to run.
