### ISSUE TITLE
X-axis label text of mutation plots cutting off, plot title text with font that is too big

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#37]
perhaps if we shrink the plot title text a little we can fit the x-label text?

**Comment by doctormo** [comment]
This is now fixed with adjusted labels.

**Comment by mahafarhat** [comment]
Labels still cutting off here is a screen shot, the second column label is "promoter_pncA"

**Comment by doctormo** [comment]
Looks like the static files aren't up to date. Because the labels aren't 45 degrees any more.

**Comment by doctormo** [comment]
I've increased the width of the y-axis labels because they were clipping too. And I've deployed the x-axis fix.
