### ISSUE TITLE
incorporate display of heatmap output on predict page

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#4]
Currently the predict page only intakes fastq or vcf files and triggers the pipeline, and checks for completion, we need it to also fetch the heatmap html file output from the output directory.

**Comment by mahafarhat** [comment]
Note this include both fetching and displaying the

 heatmap on the result page. Here is an example of the what the final output page should look like (the heatmap is in the top panel). 

![predict_output_page](https://cloud.githubusercontent.com/assets/8130645/13783130/726edb1c-eaa0-11e5-8483-e3c6e0fc8ecd.jpg)

**Comment by doctormo** [comment]
Complete for me.
