### ISSUE TITLE
Manual prediction doesnot complete processing

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#41]
Please look at latest dataset "test" that has not completed processing despite >12hours. Not sure where it's getting stuck

**Comment by doctormo** [comment]
The error was within the R script:

Error in eval(expr, envir, enclos) :
  object 'SNP_CN_2155168_C944G_S315T_katG' not found
Execution halted
1 at /www/gentb.hms.harvard.edu/apps/predict/pipeline/bin/bsubAnalyseM.pl line 12.

**Comment by doctormo** [comment]
After talking with Maha, we need to use the variant list from the repository in the database. This problem is from using the wrong format in the SNP names and replacing them with the right format should help.

**Comment by mahafarhat** [comment]
I'm attaching a new database of mutations, genes, and drug that should fix the problem. Please upload and check.
[variant_name_list_gene_drug.xlsx](https://github.com/IQSS/gentb-site/files/507124/variant_name_list_gene_drug.xlsx)

**Comment by doctormo** [comment]
There's a few problems with the new list. Trying to add them in leads to:

 * SNP_CZ not recognised as a valid SNP type.
 * CIP/Fluoroquinolones having no mutations assigned
 * EMB produces many unusual gene locus names and it looks like a broken parse. A17V, A182V etc

**Comment by mahafarhat** [comment]
Ok CIP should have the same mutations as OFLX or LEVO

**Comment by mahafarhat** [comment]
Found another issue:
when parsing 
DEL_I_1471838_d8TGTTTGGG_inter_murA_rrs
the locus name is intergenic_rrs and not intergenic_murA_rrs

**Comment by doctormo** [comment]
Ah so these items are much more complex parsing that originally considered. I think I will look for 'inter' and consider everything after that to be part of the locus name.

It's different from just taking the end version.

**Comment by mahafarhat** [comment]
thank you. let me know when it's completed.

**Comment by mahafarhat** [comment]
mutations loaded correctly, but manual prediction giving error after manual entry of mutations. No new dataset is displaying under the dataset tab

**Comment by doctormo** [comment]
Different error to the previous one, deployment error regarding lack of database permissions from orchestra. Please try again.

**Comment by mahafarhat** [comment]
processing but much too slow, the prediction from matrix step should not take more than a minute

**Comment by doctormo** [comment]
If it's still processing after 5 minutes, it's likely an error. Maybe even the same error as this one.

**Comment by doctormo** [comment]
The error was:

> Error in eval(expr, envir, enclos) :
>   object 'SNP_P_2726141_C52A_promoter_ahpC' not found
> Execution halted
> 1 at /www/gentb.hms.harvard.edu/apps/predict/pipeline/bin/bsubAnalyseM.pl line 12.
>

**Comment by mahafarhat** [comment]
ok it was missing a few mutations from the list, I added them and it's now running! will close this
