### ISSUE TITLE
Add quality control step for fastq and vcf processing

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#42]
checks coverage at important mutations and returns poor coverage error if >5% are at less than 20x coverage

**Comment by mahafarhat** [comment]
Ok so I'm working on generating a file called <strainname>.qc that will appear in the output folder for each processed strain. I will write some code the processes this file and then will generate a pass or fail for each strain. Let's start working on how we should feed this information back to the user. If the strain is QC fail no prediction should be reported regardless.

**Comment by mahafarhat** [comment]
Ok so I've tested changes to the pipeline that allow for the generation of the qc file and also another short python script that process this output and produces a PASS or FAIL to standard error. How would you like to implement feedback to the site/user. Let's talk about this tomorrow if there is time.

**Comment by mahafarhat** [comment]
This is the python script we talked about:

#reads a .qc file (supplied as a command line argument) and produces a PASS if <2% of DR region sites are covered by less than 15 reads, and FAIL if >=2% of sites are low coverage

import os
import sys
filename=sys.argv[1]
n=0
m=0
for line in open(filename):
        n=n+1
        depth=line.rstrip().split('\t')[2]
        if depth<15:
           m=m+1

if m/n < 0.02:
        print >>sys.stderr, 'PASS'
else:
        print >>sys.stderr, 'FAIL : 2% or more of the DR sites have limited coverage'

**Comment by mahafarhat** [comment]
not indentation is now completely off after copy/paste

**Comment by mahafarhat** [comment]
pushed the bsubAnalyse.pl changes to generate the qc file. 
Also I'm wondeirng if the feedback.pl script is the right place to analyze the qc. although please note that qc is only relevant to fastq prediction and not for manual or vcf prediction

**Comment by mahafarhat** [comment]
Martin we have an issue with deploying changes from the repository to orchestra, I'm now reviewing to see if this was implemented (the change code is 678644d) and it not in the appropriate folder /apps/predict/pipeline/bin/bsubAnalyse.pl doesnot have the changes and the DR_regions.BED file is not in the bin folder.

What should we do to make sure that commits get transfered to orchestra? are you doing this manually each time?

**Comment by doctormo** [comment]
There is an automatic process, but it does have issues. The files not being in the right places is not one of the known issues.

Doing a `git pull` from within the website folder will update all the files (it won't restart the webserver) and from there you can see what commits are on live.

It sounds like the live branch is causing some issues. We should probably switch to a feature branch system and we can talk tomorrow about that.

**Comment by mahafarhat** [comment]
import os
import sys

path=sys.argv[1]

for filename in os.listdir(path):
    if filename.endswith(".qc"):
        sys.stderr.write(filename[:-3])
        sys.stderr.write("\t")
        n=0
        m=0
        for line in open(filename):
            n=n+1
            depth=line.rstrip().split('\t')[2]
            if int(depth)<15:
                m=m+1
        p=(m*100)/n
        if n==0:
            sys.stderr.write('QC file empty!')
        elif p < 2:
            sys.stderr.write('PASS ')
#            sys.stderr.write(str(n))
        else:
            sys.stderr.write('FAIL : ')
            sys.stderr.write(str(p))
            sys.stderr.write('% of the DR sites have coverage <15x')
        sys.stderr.write("\n")

**Comment by mahafarhat** [comment]
This now exists
