### ISSUE TITLE
mutation plot x-axis not refreshing accurately when moving from one drug to the other

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#44]
clicking INH you get:

![crowded xaxis fw](https://cloud.githubusercontent.com/assets/8130645/19200451/089a8eae-8c97-11e6-8b3e-5347899c71b2.png)

then clicking RIF you get:
![incorrect x-axis fw](https://cloud.githubusercontent.com/assets/8130645/19200492/549fe20e-8c97-11e6-9155-2bc80e1deb97.png)

but if you refresh the page the click RIF you get an accurate plot with promoter rpoB and rpoB on the X-axis!

**Comment by doctormo** [comment]
Fixed, required a refactoring of the heatmap/graph y_axis code to make sure the paragraph tags were persistent, not duplicate and updated with the correct value.
