### ISSUE TITLE
Manual input: allow user to filter down mutations by entering a few characters that match mutation

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#45]
in the mutation drop down the user should be able to filter down the options by  entering a few matching characters. The list of mutations is now long and it's difficult to look through without further filtering. We should also sort the mutations before displaying them preferably by the second field. The second field is a 1-6 digit integer indicating the genomic coordinate of the mutation)

**Comment by doctormo** [comment]
I've fixed by using a datalist and improved the css to make it look better.
