### ISSUE TITLE
Other mutations not showing in plot

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#49]
I need to see why other mutations are not ending up in json file after manual entry

**Comment by doctormo** [comment]
I am not sure what you mean. The plot when you click on the heatmap? Those gene-locus on the x-axis as selected by applicability to the selected drug.

Otherwise, I don't know.

**Comment by mahafarhat** [comment]
I believe the issue is in generating the json file. I have yet to see "other mutations" in the mutation plots (grey bars), and at the moment that's because this data is missing from the json file itself. I will look into it and update this issue.

**Comment by mahafarhat** [comment]
ok I committed a change hopefully it did the trick, please deploy when you get a chance

**Comment by mahafarhat** [comment]
Couldn't figure out the cherry pick, do you mind deploying this change for now

**Comment by doctormo** [comment]
On Tue, 2016-11-08 at 08:42 -0800, Maha wrote:
> Couldn't figure out the cherry pick, do you mind deploying this
> change for now

No problem. Pushed live now, won't effect any existing prediction.

Martin,

**Comment by mahafarhat** [comment]
btw this is not deployed yet, just tried to test it and it didnot work so checked the orchestra TBpredict.R and it's still the old version.

**Comment by doctormo** [comment]
Can you mention which commit isn't on live yet? I just pulled in your changes from the other commit.

**Comment by mahafarhat** [comment]
"fix for other mutation bug"
d244a26

**Comment by mahafarhat** [comment]
This is still not on live, can you please check on it

**Comment by doctormo** [comment]
A manual investigation on live shows that the change in d244a26 is on live, the file `R/TBPredict.R` has the changes you've made.

**Comment by mahafarhat** [comment]
but it's not on orchestra, the TBPredict.R script on orchestra is the old version

**Comment by doctormo** [comment]
No, the version on orchestra is the new version. Are we looking in the same place? Can you give the full path the file you're looking at?

**Comment by mahafarhat** [comment]
This is the path /www/gentb.hms.harvard.edu/apps/predict/pipeline/bin/TBPredict.R
the script there is not updated with change d244a26

**Comment by doctormo** [comment]
I thought that this might be the issue. The change d244a26 does not change file `apps/predict/pipeline/bin/TBPredict.R` but file `R/TBPredict.R`, having these duplicate files in two places in the codebase has been the root cause of the issue.

We should delete the R directory if possible and make sure we don't have any duplicate files. If possible we should make sure the two files have all the changes from each other.

**Comment by doctormo** [comment]
Would you like me to manually sort this out? I might not know all the changes to look for though.

**Comment by mahafarhat** [comment]
it's ok I can manually put in the changes into apps/predict/pipeline/bin/TBpredict.R
we should delete TBpredict.R from the R/ directory. I will do that and commit to master

**Comment by doctormo** [comment]
Great, since you've manually edited live, I'm going to hold off on deploying to live. When we do a deploy, remind me that we need to clean up the manual changes.

**Comment by mahafarhat** [comment]
this is now resolved, we have a new different issue for mutation display
