### ISSUE TITLE
promoter mutation not displaying in plot

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#50]
by manual entry I selected this mutation:
SNP_P_1673425_C15T_promoter_fabG1.inhA
which is an important mutation for inh and eth resistance (it shows up in the json file) in the following folder:
/groups/gentb_www/predictData/tbdata_00000049

but at the moment this is not displaying in the plot, not sure why (see dataset title strain123)

**Comment by doctormo** [comment]
This issue might be that the promoter title doesn't match the database title for the axis control. Check database version against that in the data.
