### ISSUE TITLE
Describe dv genotype phenotype columns

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#51]
In order to create good database models from the csv data, we need to be able to re-group the columns from `shinyapps.io/genTB/dv_genotype_phenotype_with_country.csv` into their appropriate tables.

#7 depends on this issue. This is the data so far with their unique counts:

Strain Mutation:
 * old_id: 156887
 * snpname: 26950
 * ResistanceType: 5
 * IsoniazidDST: 4
 * EthionamideDST: 4
 * RifampicinDST: 3
 * RifabutinDST: 3
 * EthambutolDST: 3
 * PyrazinamideDST: 3
 * StreptomycinDST: 3
 * AmikacinDST: 3
 * CapreomycinDST: 4
 * KanamycinDST: 3
 * OfloxacinDST: 4
 * CiprofloxacinDST: 3
 * LevofloxacinDST: 3
 * MoxifloxacinDST: 4
 * GatifloxacinDST: 3
 * ParaAminoSalicylicAcidDST: 4
 * CycloserineDST: 3
 * ThioacetazoneDST: 3
 * ProthionamideDST: 3
 * ClofazimineDST: 3
 * ClarithromycinDST: 3
 * AmoxicillinClavulanateDST: 3
 * LinezolidDST: 3:
 * + Strain/Sample

Strain/Sample:
 * strain: 1862
 * Name: 1843
 * Date: 866
 * City: 19
 * Source: 17
 * + Patient
 * + Country

Patient:
 * PatientID: 621
 * PatientAge: 48
 * PatientSex: 3
 * HIVStatus: 2

Duplicate Data from snpname (thrown away):
 * sub.ins.del: 4
 * coding.silent: 13
 * genomic.coordinate: 26656
 * genetic.change: 13014
 * amino.acid.change: 16761
 * region: 5027

Country:
 * Country_code: 78
 * Country: 78
 * lat: 59
 * lon: 62

Unknown:
 * Setting: 47
 * Spfamily_parentstrain: 10
 * RFLPfamily: 62
 * Spoligo_octal: 3

**Comment by mahafarhat** [comment]
you can place all of the following into one strainsourcedata table:
Unknown

    Setting: 47
    Spfamily_parentstrain: 10
    RFLPfamily: 62
    Spoligo_octal: 3

Strain/Sample:

    strain: 1862
    Name: 1843
    Date: 866
    City: 19
    Source: 17
    + Patient
    + Country

Patient:

    PatientID: 621
    PatientAge: 48
    PatientSex: 3
    HIVStatus: 2

**Comment by mahafarhat** [comment]
we should have three 4 total tables in the database:

(1) strainsourcedata as above
(2) strain_mutation table
(3) mutation table
(4) DST table

I currently have these data in a MySQL dump, but the field names are a little different, and they are in two separate databases. Would it help to have these?

**Comment by doctormo** [comment]
The MySQL dump would be useful, we can put it on dropbox for dissection. Are these data up to date with the csv data?

**Comment by mahafarhat** [comment]
database: wgsmtb

mysql> select * from strainsourcedata limit 2;
+----+---------+--------------+-------------+------------+--------------+--------------+---------------+--------------------+-------+-------+-----------+--------+---------+--------+------------+-----------------------+-----------+-------------------+-----------+--------------------+
| id | name    | otherid      | clustername | date       | country      | city         | setting       | source             | ptage | ptsex | hivstatus | sptype | inttype | IS6110 | RFLPfamily | spfamily_parentstrain | patientid | SNP_cluster_group | SNP_set   | SNP_cluster_group2 |
+----+---------+--------------+-------------+------------+--------------+--------------+---------------+--------------------+-------+-------+-----------+--------+---------+--------+------------+-----------------------+-----------+-------------------+-----------+--------------------+
|  1 | M224HiQ | St-05:TB2706 | MINE        | 2004-07-02 | South Africa | Stellenbosch | Mine outbreak | Tommie Victor, PhD |    34 | M     | NULL      | 22     | 92      | 330    | 140        | LCC                   | 5692      | SCG4              | GGCCATTCC | SCG4               |
|  2 | M230HiQ | St-06:TB606  | MINE        | 2006-08-31 | South Africa | Stellenbosch | Mine outbreak | Tommie Victor, PhD |    36 | M     | NULL      | 22     | 92      | 330    | 140        | LCC                   | 5692      | SCG4              | AGCCATTCC | SCG4*              |
+----+---------+--------------+-------------+------------+--------------+--------------+---------------+--------------------+-------+-------+-----------+--------+---------+--------+------------+-----------------------+-----------+-------------------+-----------+--------------------+
2 rows in set (0.01 sec)

mysql> select * from straindrugresistance limit 2;
+-----+--------+--------+------+------+------+------+------+------+------+------+------+------+-------+------+-------+------+------+------+
| ID  | name   | drtype | rinh | reth | rrif | rrfb | remb | rpza | rstr | ramk | rcap | rkan | roflx | rcip | rlevo | rpas | rcys | rtha |
+-----+--------+--------+------+------+------+------+------+------+------+------+------+------+-------+------+-------+------+------+------+
| 110 | MT0030 | S      | s    | NULL | s    | NULL | s    | s    | s    | NULL | NULL | NULL | NULL  | NULL | NULL  | NULL | NULL | NULL |
| 109 | MT0029 | S      | s    | NULL | s    | NULL | s    | s    | s    | NULL | NULL | NULL | NULL  | NULL | NULL  | NULL | NULL | NULL |
+-----+--------+--------+------+------+------+------+------+------+------+------+------+------+-------+------+-------+------+------+------+
2 rows in set (0.00 sec)

mysql> select * from strain_snps_h37rv limit 2;
+----+-----------+---------+-------+
| id | snpid     | cnsqual | depth |
+----+-----------+---------+-------+
| 92 | 1003515CT |     255 |   255 |
| 92 | 1003545AG |     255 |   255 |
+----+-----------+---------+-------+
2 rows in set (0.00 sec)

mysql> select * from snps_h37rv limit 2;
+-----------+---------------------------+---------+-------+-------+-------+-------+-------+------+--------+--------+------------+------------+-------------+
| snpid     | snpname                   | ntpos   | ntref | ntvar | aapos | aaref | aavar | syn  | coding | geneid | genesymbol | mrna_ntpos | ecoli_aapos |
+-----------+---------------------------+---------+-------+-------+-------+-------+-------+------+--------+--------+------------+------------+-------------+
| 4217002GA | SNP_N_4217002_G55A_Rvnt44 | 4217002 | G     | A     |  NULL | NULL  | NULL  | NULL | N      | Rvnt44 | NULL       |       NULL |        NULL |
| 2969970CT | SNP_N_2969970_C29T_Rvnt34 | 2969970 | C     | T     |  NULL | NULL  | NULL  | NULL | N      | Rvnt34 | NULL       |       NULL |        NULL |
+-----------+---------------------------+---------+-------+-------+-------+-------+-------+------+--------+--------+------------+------------+-------------+
2 rows in set (0.00 sec)

**Comment by mahafarhat** [comment]
database gtbdr

mysql> select * from gtbdr.strainsourcedata limit 2;
+------+--------------+---------+-------------+--------+------------+------+---------+--------+-------+-------+-----------+--------+---------+--------+------------+-----------------------+------+-----------+---------------+
| id   | name         | otherid | clustername | date   | country    | city | setting | source | ptage | ptsex | hivstatus | sptype | inttype | IS6110 | RFLPfamily | spfamily_parentstrain | PGG  | patientid | spoligo_octal |
+------+--------------+---------+-------------+--------+------------+------+---------+--------+-------+-------+-----------+--------+---------+--------+------------+-----------------------+------+-----------+---------------+
| 1701 | NLA000000560 |         |             | Jan/00 | Azerbaijan |      | RIVM    |        |     0 |       |           |   NULL |         |        |            |                       |    3 | NULL      | NULL          |
| 1702 | NLA000000636 |         |             | Mar/00 | unknown    |      | RIVM    |        |     0 |       |           |   NULL |         |        |            |                       |    2 | NULL      | NULL          |
+------+--------------+---------+-------------+--------+------------+------+---------+--------+-------+-------+-----------+--------+---------+--------+------------+-----------------------+------+-----------+---------------+
2 rows in set (0.00 sec)

mysql> select * from gtbdr.straindrugresistance limit 2;
+-----+------+--------+------+------+------+------+------+------+------+------+------+------+-------+------+-------+------+------+------+------+-------+-------+-------+-------+-----------+------+-----------+--------+---------+--------+------------+-----------------------+-----------+---------------+
| ID  | name | drtype | rinh | reth | rrif | rrfb | remb | rpza | rstr | ramk | rcap | rkan | roflx | rcip | rlevo | rpas | rcys | rtha | rpro | rclof | rmoxi | rclar | rgati | ramoxclav | rlin | hivstatus | sptype | inttype | IS6110 | RFLPfamily | spfamily_parentstrain | patientid | spoligo_octal |
+-----+------+--------+------+------+------+------+------+------+------+------+------+------+-------+------+-------+------+------+------+------+-------+-------+-------+-------+-----------+------+-----------+--------+---------+--------+------------+-----------------------+-----------+---------------+
| 101 | 1    | MDR    | r    | NULL | r    | NULL | r    | r    | r    | s    | NULL | NULL | NULL  | NULL | NULL  | NULL | NULL | NULL | NULL | NULL  | NULL  | NULL  | NULL  | NULL      | NULL | NULL      | NULL   |    NULL | NULL   | NULL       | NULL                  | NULL      | NULL          |
| 102 | 2    | MDR    | r    | NULL | r    | NULL | r    | r    | r    | r    | NULL | NULL | NULL  | NULL | NULL  | NULL | NULL | NULL | NULL | NULL  | NULL  | NULL  | NULL  | NULL      | NULL | NULL      | NULL   |    NULL | NULL   | NULL       | NULL                  | NULL      | NULL          |
+-----+------+--------+------+------+------+------+------+------+------+------+------+------+-------+------+-------+------+------+------+------+-------+-------+-------+-------+-----------+------+-----------+--------+---------+--------+------------+-----------------------+-----------+---------------+
2 rows in set (0.00 sec)

mysql> select * from gtbdr.strain_var_h37rv limit 2;
+-----+-----------+------+-------+-------+------+--------+------+-------+
| id  | snpid     | qual | depth | bidir | hqr  | hqrref | fq   | aavar |
+-----+-----------+------+-------+-------+------+--------+------+-------+
| 101 | 3074519iG |  200 |   658 | N     |  302 |    356 |   48 |       |
| 102 | 3074519iG |  200 |   278 | N     |  160 |    118 |   56 |       |
+-----+-----------+------+-------+-------+------+--------+------+-------+
2 rows in set (0.02 sec)

mysql> select * from gtbdr.var_h37rv limit 2;
+-----------+---------------------------------+---------+-------+-------+-------+-------+-------+------+--------+---------+------------+------------+-------------+----------+----------+----------+
| snpid     | snpname                         | ntpos   | ntref | ntvar | aapos | aaref | aavar | syn  | coding | geneid  | genesymbol | mrna_ntpos | ecoli_aapos | refcodon | varcodon | codonpos |
+-----------+---------------------------------+---------+-------+-------+-------+-------+-------+------+--------+---------+------------+------------+-------------+----------+----------+----------+
| 1917972AG | SNP_CS_1917972_A33G_L11L_tlyA   | 1917972 | A     | G     |    11 | L     | L     | S    | C      | Rv1694  | tlyA       |         33 |           0 | CTA      | CTG      |        3 |
| 2155168CG | SNP_CN_2155168_C944G_S315T_katG | 2155168 | C     | G     |   315 | S     | T     | N    | C      | Rv1908c | katG       |        944 |           0 | AGC      | ACC      |        2 |
+-----------+---------------------------------+---------+-------+-------+-------+-------+-------+------+--------+---------+------------+------------+-------------+----------+----------+----------+
2 rows in set (0.03 sec)

**Comment by doctormo** [comment]
I think this is enough information for the description issue. Closing.
