### ISSUE TITLE
Notes from Mike

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#57]
**Homepage**
- [x] Terms of Use/Supporters/Contact/Cite/FAQs block clean up layout -- the collapsable panels don’t provide much UX value
- [x] Citation, “Murray M” listed twice
- [x] Citation, does the URL need to be a link?
- [x] Contact Information panel has a bad URL, that returns a 404, the correct URL for that link should be “mailto:tbpredict@gmail.com”
- [x] Page title for browser window only reads “- genTB” and should have a brief description here, maybe “genTB - Translational Genomics of Tuberculosis”

**Footer**
- [x] Update Dataverse Project logo (updated logo can be found at Dataverse in GitHub)

**Predict**

- [x] All of the prediction method titles include “New”, since the site is new, and all these methods are labeled new, do we need to explicitly label them as such? (I also wanted to say all “Prediction” was also too redundant, but I can understand if that is necessary)
- [x] Since “Variant Call Format” is often referred to as “VCF” in the site, maybe include that in parentheses in the section title, “Variant Call Format (VCF) Prediction”
- [x] “New Variant Call Format Prediction” description, the link “More information” shouldn’t be capitalized and the URL points to this same Predict pg, also “vcf” should be capitalized
- [x] “New Manually Entered Prediction” description, “vcf” should be capitalized
- [x] There is a thin gray line at the top of the column on right-side of page, remove this column if it’s not needed and let the content extend full width
- [x] When the browser window is narrow (~1020px), the footer copyright and links shoots right into this extra column space
- [x] Page title for browser window only reads “Create Prediction - genTB” and should been consistent with the heading “Predict - genTB”

**Predict > FastQ Pair-Ended**

- [x] Info/help text is restricted to column on left-side of page, it should extend full-width, above both columns
- [x] “Dataset information” title should be capitalized, align left, increase font size to be equal to “FASTQ files” title
- [x] Since you have “dataset” in that section title, you shouldn’t need it in the form labels, so I suggest using just “Title” and “Description”, and no need for the colons (“:”)
- [x] “FASTQ files” title should follow the “FastQ” format style that is used on the Predict pg, “files” should be capitalized
- [x] Will there is no standard I can refer to, typically the Save/Submit buttons is on the left, and the Cancel button is on the right, there is be extra space added between them in order to avoid accidental clicks

**Predict > FastQ Single-Ended**

- [x] Info/help text is restricted to column on left-side of page, it should extend full-width, above both columns
- [x] “Dataset information” title should be capitalized, align left, increase font size to be equal to “FASTQ files” title
- [x] Since you have “dataset” in the section title, you shouldn’t need it in the form labels, so I suggest using just “Title” and “Description”, and no need for the colons (“:”)
- [x] “FASTQ files” title should follow the “FastQ” format style that is used on the Predict pg, “files” should be capitalized
- [x] Will there is no standard I can refer to, typically the Save/Submit buttons is on the left, and the Cancel button is on the right, there is be extra space added between them in order to avoid accidental clicks

**Predict > Variant Call Format**
- [x] Info/help text is restricted to column on left-side of page, it should extend full-width, above both columns
- [x] “Dataset information” title should be capitalized, align left, increase font size to be equal to “vcf file” title
- [x] Since you have “dataset” in the section title, you shouldn’t need it in the form labels, so I suggest using just “Title” and “Description”, and no need for the colons (“:”)
- [x] “vcf file” title should be capitalized, “VCF File”
- [x] Will there is no standard I can refer to, typically the Save/Submit buttons is on the left, and the Cancel button is on the right, there is be extra space added between them in order to avoid accidental clicks

**Predict > Manually Entered**

- [x] “Manual Mutations Entry” heading doesn’t follow the “New Manually Entered Prediction” heading on the previous Predict pg, they should be labeled in a consistent manner
- [x] Info/help text is restricted to column on left-side of page, it should extend full-width, above both columns
- [x] “Dataset information” title should be capitalized, align left, increase font size to be equal to “Instructions” title
- [x] Since you have “dataset” in the section title, you shouldn’t need it in the form labels, so I suggest using just “Title” and “Description”, and no need for the colons (“:”)
- [x] “Genetic information” title should be capitalized
- [x] Will there is no standard I can refer to, typically the Save/Submit buttons is on the left, and the Cancel button is on the right, there is be extra space added between them in order to avoid accidental clicks

**Data**
- [x] The two-column layout doesn’t give enough space to the Dataverse widget, I would recommend trying a tab component to display one workflow at a time
- [x] Page title for browser window only reads “Share - genTB - genTB” and should been consistent with the link that was clicking in the navbar heading “Data - genTB”

**Data > Contribute**

- [x] First sentence in first paragraph references the “Harvard Dataverse Application”, which should only be “Harvard Dataverse”
- [x] Sentence in second paragraph has “FASTQ” reference, should follow the “FastQ” format style that is used on previous pgs
- [x] Sentence in third paragraph has two links to the same page -- to avoid this, I suggest revising the sentence to read “Please view the Data Upload Instructions guide for more information on how to prepare your data for sharing.”
- [x] Step 1 should be changed to read, “Go to the Harvard Dataverse to create an account” -- that link brings the user right to the Create Account pg, and will redirect them to your Tuberculosis Dataverse, no other links should required in the following steps
- [x] Step 2 should be changed to read, “Upon creating your account, you’ll be redirected to the Tuberculosis Dataverse, then click the Add Data button, and select New Dataset.”
- [x] Last paragraph has a bad URL, that returns a 404, the correct URL for that link should be “mailto:tbpredict@gmail.com”

**Data Upload Instructions**

- [x] Link to “Dataverse” should open in a new window, and should read “Harvard Dataverse”
- [x] “Genotype data files”  title should be capitalized
- [x] “FASTQ” references should follow the “FastQ” format style that is used on previous pgs
- [x] “FASTQ paired end files”  title should be capitalized, also should it be the same font size as the other titles?
- [x] “Phenotype data files” title should be capitalized
- [x] Page title for browser window only reads “Data Upload Instructions - genTB - genTB”, the second “- genTB” should be removed

**Map**
--REDACTED

**Explore**

- [x] Help text at top of page contains two links to the same video URL. Suggest changing to read, “Please watch our tutorial video for a quick demonstration of how to use this analysis tool.”
- [x] Also, related to the demo video on YouTube, the description reads “For more information, visit http://tb.datascience.iq.harvard.edu/”, and that URL seems to point to a different (older?) installation of genTB than your current site
- [x] Clicking “Open Codebook” results in 403 Not Authorized (Harvard Dataverse), should also open in new window/tab
- [x] Iframe border around TwoRavens is heavy and could be removed or made a lighter gray

**About**

- [x] Intro sentence is formatted in italic, no other sections use this formatted style, maybe apply it to the help/info msgs on the other pages
- [x] Predict DR/Share/Map/Explore -- move these section descriptions into the help/info msgs of each page, where they’re more useful to the users
- [x] “Predict DR” section title vs. “Predict” pg used across the site, this section should be referenced in a consistent manner
- [x] “Share” section I believe is intended to describe the Data pg, this section should be referenced in a consistent manner
- [x] “Share” section has a link to “Digital Object Identifier (DOI)” that should open in a new window/tab
- [x] “Explore” section has a link to “TwoRavens” that should open in a new window/tab
- [x] “Features and Tools in Development” section has a bad URL, that returns a 404, the correct URL for that link should be “mailto:tbpredict@gmail.com”
- [x] “Training data sources are described in” section has links in the citations that should open in a new window/tab, the title should be capitalized, and read “Training Data Sources”
- [x] “Random Forest Classifier” section has a link that should open in a new window/tab
- [ ] Terms of Use/Supporters/Contact/Cite block clean up layout -- this section is the same info as on the homepage, maybe they could share a consistent layout (see quick mockup I attached below…)
- [x] “Contact” section has a bad URL, that returns a 404, the correct URL for that link should be “mailto:tbpredict@gmail.com”
- [x] “Terms of use statement” title should be capitalized
- [x] “Terms of use statement” different than the “Terms of Use” pg
- [x] Citation, “Murray M” listed twice
- [x] Citation, does the URL need to be a link?
- [x] Page title for browser window only reads “About - Phthisis Ravens - genTB”, the name “Phthisis Ravens” isn’t included anywhere else in the app, and should be removed

**Terms of Use**

- [x] “Terms of Use” pg different than the “Terms of use statement” on About pg

Tuberculosis Dataverse
Update description of the Tuberculosis Dataverse to point to the genTB app

**Sample Mockups**

- [x] Termsof Use/Cite the Project/Funding block mockup for the Home + About pgs

![mockup](https://cloud.githubusercontent.com/assets/589384/20151685/16d4fb42-a689-11e6-88b5-abd7b4d8464a.png)

**Comment by mheppler** [comment]
👍

**Comment by mahafarhat** [comment]
Adding an item to this list:

when performing manual prediction, the dataset page after hitting predict gives the following for a status:

 	Fail   File Retrieval Success (id: 5) 

Should say Success instead of fail

**Comment by mahafarhat** [comment]
This last Fail status error after manual entry is more urgent

**Comment by doctormo** [comment]
Please test Fail status now.

**Comment by doctormo** [comment]
Phew! this was a lot of stuff, now fixed!

**Comment by pdurbin** [comment]
> Update description of the Tuberculosis Dataverse to point to the genTB app

@doctormo great! The last thing I can think of is above. Basically, it would be nice if the description at https://dataverse.harvard.edu/dataverse/tuberculosis that starts with "The Tuberculosis Dataverse is a collection of datasets that" linked to https://gentb.hms.harvard.edu (HTML is allowed in the description field on the Dataverse side).
