### ISSUE TITLE
Targeting Regions

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#58]
What are the target regions tables called in the gtbdr database.

This is blocking.

**Comment by mahafarhat** [comment]
the information you need is in the "targetgenes" table in gtbdr. Here is the table description:
mysql> describe targetgenes;
+-------------+------------------+------+-----+---------+-------+
| Field       | Type             | Null | Key | Default | Extra |
+-------------+------------------+------+-----+---------+-------+
| genesymbol  | varchar(50)      | YES  |     | NULL    |       |
| h37rv_id    | varchar(20)      | YES  |     | NULL    |       |
| strand      | set('+','-','.') | YES  |     | NULL    |       |
| start       | int(11)          | YES  |     | NULL    |       |
| stop        | int(11)          | YES  |     | NULL    |       |
| length      | int(11)          | YES  |     | NULL    |       |
| type        | varchar(20)      | YES  |     | NULL    |       |
| description | varchar(255)     | YES  |     | NULL    |       |
+-------------+------------------+------+-----+---------+-------+
8 rows in set (0.00 sec)

Note that h37rv_id is the same information as geneid field in var_h37rv table in gtbdr
