### ISSUE TITLE
Duplicate Mutations, same Name

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#59]
In our mutations app we have duplicates for the same gene_locus and mutations. These gene_locus's are owned by different drugs, which is fine for the predict use, but it makes it hard to bring in the maps data as they don't have drugs attached to them in the same way.

It looks like we need to make gene_locus unique and drugs shouldn't own gene_locuses. but you will know better than me.

This is a blocker.

**Comment by mahafarhat** [comment]
Perhaps the solution is to have a separate table linking the subset of genes to their respective drugs. Not every gene will have an associated drug, but some will do, and some genes link to more than one drug.

You can deduce these relationships from the database we have for the mutations app, but if you need more information let me know

**Comment by doctormo** [comment]
OK, so I've created three migrations and moved the code to this new structure. What we have now is drugs, each drug has a list of mutations implicated in resistance. Drugs and gene locuses are no longer related directly and mutations continue to have a single gene locus each.

All duplications are merged in the second of the new migrations. Maha, if ever your interested in how django does schema management and data migrations, this is a good example to show.
