### ISSUE TITLE
Allow download of predict pipeline intermediary files

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#6]
these are the .vcf and .var files that are stored in the same output folder as the .html, .json and other output files that are generated by the predict pipeline. We need to build the website to allow the user to request these files and be able to receive them.

**Comment by mahafarhat** [comment]
Note these files are the .vcf file and .var files that appear in the output folder after processing a FASTQ, and the .var files that appear in the output folder after processing a VCF. 

Given that you now have the pipeline, and can test it please go ahead on this aim

**Comment by mahafarhat** [comment]
Martin raised a concern about ease of access to these files and privacy/security concerns related to this. These will need to be addressed at a later date

**Comment by doctormo** [comment]
This is now done.
