### ISSUE TITLE
Log in Error

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#60]
getting the following error when I try to log in using firefox:

Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

**Comment by doctormo** [comment]
Test just now as working. Could you hard refresh for me and see if a stale cookie in your browser is to blame? [Ctrl]+[F5]

**Comment by mahafarhat** [comment]
tried hard refresh, restarting the browser and restarting my computer to no avail

**Comment by doctormo** [comment]
Can you post a link to the offending page? Maybe something's happened and I can't see it?

**Comment by mahafarhat** [comment]
its fixed now! not sure why

**Comment by doctormo** [comment]
We'll keep an eye open for it in the future.
