### ISSUE TITLE
"add" button not working for manual prediction using microsoft edge

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#61]
drop down list for mutations is acting strangely, list is slow to appear and is in very large font, and is also misplaced relative to the mutations box. Once a mutation is selected clicking on "add" does not result in addition of the mutation to the list

**Comment by doctormo** [comment]
This will be very hard for be to test since Microsoft Edge isn't available for any of my computers. I might need to work with someone on Friday to resolve the issue.

**Comment by doctormo** [comment]
We might want to add a warning message for edge users that the website hasn't been tested with the browser.
