### ISSUE TITLE
Strain Mutation Repeats

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#62]
Sometimes a mutation is repeated in the table strain_var_h37rv for example:

{"bidir": "N", "snpid": "1473136AT", "aavar": "", "fq": 69, "hqr": 102, "qual": 200, "depth": 127, "hqrref": 25, "id": 1514},
{"bidir": "N", "snpid": "1473136AT", "aavar": "", "fq": 68, "hqr": 245, "qual": 200, "depth": 272, "hqrref": 27, "id": 1514},
{"bidir": "N", "snpid": "2726338TG", "aavar": "G", "fq": 40, "hqr": 252, "qual": 200, "depth": 267, "hqrref": 15, "id": 1514},
{"bidir": "N", "snpid": "2726338TG", "aavar": "G", "fq": 39, "hqr": 420, "qual": 200, "depth": 456, "hqrref": 36, "id": 1514},

This shows two strain mutations, two slightly different bits of data.

**Comment by mahafarhat** [comment]
ok depth should be equal to hqr+hqrref

We see this because some strains were sequenced twice.

**Comment by mahafarhat** [comment]
I should say this is an unusual situation particular to this dataset, you can go ahead and ignore repeats mutations, but pick the one with the higher depth count.
