### ISSUE TITLE
Country use

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#65]
The mutations app should use a dedicated country model.

**Comment by doctormo** [comment]
The cleanup of country data from gtb data set produces this data map:

MAP = {
    'unknown': None,
    'South Afica': 'South Africa',
    'Ivory Coast': 'CIV',
    'Netherland': 'Netherlands',
    'Camerun': 'Cameroon',
    'Trinidad & Tobago': 'Trinidad and Tobago',
    'Kazakstan': 'Kazakhstan',
    'Kazachstan': 'Kazakhstan',
    'Brasil': 'Brazil',
    'Azerbaidjan': 'Azerbaijan',
    'Marocco': 'Morocco',
    'DR Congo': 'Democratic Republic of the Congo',
    'RD Congo': 'Republic of Congo', # Is this right?
    'Guinea Eq.': 'Equatorial Guinea',
    'Burma': 'Myanmar',
    'Abkhazia': 'Georgia', # Should be added to our db, data loss.
    'Netherlands Antilles': None, # Doesn't exist in our db, data loss.
    'Guinea-Conakry': 'Guinea', # Contains city, naughty. data loss.
    'China /Tibet': 'China', # Region, data loss
    'Tibet': 'China', # Region, data loss
    'Carribean': 'Aruba', # Region to country map, data loss
}

There is no city data in any of the records.

**Comment by mahafarhat** [comment]
RD Congo is also 'Democratic Republic of the Congo' (RD=republique democratique )
let's keep a 'notes' field in the table to describe this loss of info, 
-->for Netherlands Antilles can use Saint Maarten (hopefully this exists in the db), noting that it was "Netherland Antilles" in the notes
-->for Abkhazia I would add this to our database 
-->Guinea-Conakry is a commonly used term by the French to distinguish between Guinea and equitorial guinea, we can safely assume that there is no city info here
-->For tibet, I would add this to our database and make a note 
-->agree with aruba just make a note
