### ISSUE TITLE
Source quality is often negative

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#66]
Th values in gtbdr database under the column fq in table strain_var_h37rv are almost always negative. The quality field is often positive (depth?)

**Comment by doctormo** [comment]
This data point should be named correctly. Give to maha to fix.

**Comment by mahafarhat** [comment]
for now just leave this as is. I will get it to it, but it's low on my priority list

**Comment by doctormo** [comment]
I'm going to keep it as mapping_quality to make it 10% clearer and we can rename it later if needed. I'll keep the label and help_text specific.
