### ISSUE TITLE
Old data settings value

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#67]
These items are in the settings column and need translating.

- Endemic beijing
- highly transmitted in NYC
- FZB Lineage6
- FZB Lineage5
- patient-1 RFLP w1 1/5 cases from contam b-scope
- mine
- FZB Lineage1
- Endemic strain(s) from identical spoligocluster with progressive resistance
- RIVM Lineage2
- derived from lung extracts of patient with original H37 strain
- Lab generated mutant with isolated low level kanamycin resistance
- isolated in SF Lineage4B
- Community outbreak  with identical spoligotype
- isolated from a single host during the course of a chronic infection
- RIVM Lineage4C
- RIVM Lineage4B
- Endemic Beijing
- Outbreak Northern BC
- Multiple countries, first isolated in Haarlem, The Netherlands
- Endemic strain(s) from identical spoligocluster with variable levels of resistance
- |N
- Endemic beijing family strain(s) with relatively low transmission
- isolated in SF from patient born in China Hirsh et al 2004 Lineage3C
- Philip Hopewell
- Virulent reference beijing
- None
- isolated from patient in Gambia 2002 previously analyzed by genomic deletion analysis Gagneux et al 2006 Lineage1
- Single IV-Drug User with non-compliance
- russian clin isolate w high level cap resistance
- highly drug resistant
- isolated in SF Lineage3C
- isolated in SF Lineage3B
- clin isolate w unknown mech pza resistance
- RIVM LineageM_canettii
- Community outbreak  with progressive resistance with similar but non identical spoligotype
- isolated in SF from patient born in Philipines Hirsh et al 2004 Lineage4A
- RIVM Lineage3A
- RIVM Lineage1
- Endemic beijing-low-copy-clade family strain(s) with relatively low transmission
- 2177-N / clin isolate in college student travel to india com to another pt
- isolated in SF Lineage6
- Mine outbreak
- isolated in SF Lineage2 Philip Hopewell
- russian clin isolate w low level kan resistance

**Comment by mahafarhat** [comment]
Ok can you please send me the name, source and setting field info for each of these.

I think we will need to rename the "Source" field to a field called "LaboratorySource", and move all the RIVM/MSLI/CDC etc "setting" data from gtbdr to this laboratory field. 

For the wgsmtb data, erase the source data as it is (current a researcher's name) and replace with the following info for each line of data:

Name: LaboratorySource
borowski\d: UCSF
CDC-\d+: CDC
\d\d-R\d+: MSLI  
H37Ra: NCBI
K-\d: FZB
X122: Stellenbosch 
R1207: Stellenbosch 
R\d[3]\w?: Stellenbosch 
 w-148: PHRI/NCBI
c: PHRI/NCBI
M\d{2-3}\w?: Stellenbosch
haarlem: PHRI/NCBI
MT00\d\d: BCCDC
HN878: NCBI
MTB210: NCBI
K\d{2}\d?: RIVM
\d{4-5}_\d{2}: FZB
T\d{2}: UCSF
GM_0981: UCSF
\d{2}_\d{4}: UCSF
M4100: UCSF

If not listed above leave LaboratorySource blank

Please also make the following corrections to the data:
M4100 country is: South Korea, setting is: isolated in SF lineage 3A, city is NULL

If there is a reference eg. agerton 1997 JAMA; Maus, AAC; Sacchettini, Ioerger BMC Genomics 2010 etc in the current course field please add this to the setting field using comma as a separator between the current info and this new info, and then replace source with laboratorysource data as I detail above.

thank you!
