### ISSUE TITLE
Decide on coding strategy and approach to convert maps from R to python

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#7]
This will have to be d3 based, question is which wrapper to use, need to decide on this, and then define the task list to achieve this milestone.

**Comment by mahafarhat** [comment]
Note that relevant files are currently located under the shinyapps.io folder and the apps/maps folder

**Comment by doctormo** [comment]
- There are csv files which contain the majority of the data, a large file (44MB) contains the details
- All csv data should be converted into database tables and stored
- django-leaflet and geojson can be used to display the information to the user
- The mutations search tab is not correct and will need to be re-engineered

**Comment by doctormo** [comment]
I think we have the design layout done.
