### ISSUE TITLE
manual prediction matrix is too large 

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#71]
Matrix generated by manual prediction input currently allows too many variables (essentially all that are in the database), we need to limit these to the 992 variables that are in the variable_name_list.csv file in the bin folder. This will speed up the processing considerably.

**Comment by doctormo** [comment]
I imagine this data being folded into the database such that Mutation table contains a BooleanField "predictor" with a help_text="This mutation is selected to be used in predictions and will be shown to users in the manual mutation selection process."

Is this a good plan?

**Comment by mahafarhat** [comment]
yes that should work well!

**Comment by doctormo** [comment]
This is now fixed.
