### ISSUE TITLE
Varient list creator should come out of pipeline code.

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#72]
I'd like to get the variant_list.py file folded into the site code as well, as it'd be helpful to keep all the data in the same place.

This is related to issue #71 where we want to fold in the csv data to the database. So it only makes sense to also fold in the generator code too.

**Comment by doctormo** [comment]
The generate_matrix.py file would also come out of the pipeline and be a process that uses the database data.

**Comment by mahafarhat** [comment]
yes that's fine, makes sense to make the generate_matrix.py fetch the variant_name_list.csv (variant subset used for prediction) from the database to allow easier updates in the future.

**Comment by mahafarhat** [comment]
btw the variant_name_list.csv file contains the list of potential predictors

**Comment by doctormo** [comment]
All mutations in variant_name_list.csv have been marked as predictors in the database. No problems or missing mutations from the database.

The next step is to generate the csv file for the pipeline.
