### ISSUE TITLE
Clean up Snpnames

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#75]
In the website database, the wgs snps are labeled without an mrnaposition, and the targeted sequencing strains are labeled with an mrna position. I need to clean these up to avoid inaccuracies in mapping

eg. SNP_CZ_2155101_G1011C_Y337._katG
vs.  SNP_CZ_2155101_GC_Y337._katG

**Comment by doctormo** [comment]
These are the affected mrnapos issues:
[mrnapos.txt](https://github.com/IQSS/gentb-site/files/850796/mrnapos.txt)
