### ISSUE TITLE
intermediate file upload links are broken

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#77]
under the output files tab the links to the files are not working: the links look something like this
https://gentb.hms.harvard.edu/tb/media/datatbdata_00000076/Italian1.sam

I think they should be:

https://gentb.hms.harvard.edu/data/media/data/tbdata_00000076/Italian1.sam

but even when I correct this I get a 404 error, is it a permissions issue, are these just links to the data under the /groups/gentb_www/ folder?

**Comment by doctormo** [comment]
The correct url is:

https://gentb.hms.harvard.edu/tb/media/data/tbdata_00000076/Italian1.sam there's a missing slash in the url.

**Comment by doctormo** [comment]
Now fixed and made live.
