### ISSUE TITLE
Move predict dependencies into new less private location on orchestra

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#8]
This will include predict pipeline, test folder and files and data storage folders.

1- I am awaiting input from Orchestra on the new location
2- Will need to confirm that Martin has access to the new location.
3- Will need to run this by Raman, he has already provided the following input by email:

To change the value in production.
(1) Open this file:
    /www/gentb.hms.harvard.edu/code/gentb-site/gentb_website/tb_website/tb_website/settings/secret_settings_prod_hms.json
(2) Change the value of variable “TB_SHARED_DATAFILE_DIRECTORY”
(3) You probably have to restart the server (supervisord):
https://github.com/IQSS/gentb-site/blob/master/docs/ORCHESTRA-SETUP.md#stop-and-restart-supervisord
——————————————
(extra information)
Settings file references (buried) in the docs are here:
   https://github.com/IQSS/gentb-site/blob/master/docs/ORCHESTRA-SETUP.md#add-production-settings
Where the  “TB_SHARED_DATAFILE_DIRECTORY” value is pulled into the Django code:
    https://github.com/IQSS/gentb-site/blob/master/gentb_website/tb_website/tb_website/settings/production_hms.py#L116

**Comment by mahafarhat** [comment]
So I have now moved the predict pipeline and test folders to 
/www/gentb.hms.harvard.edu/code/gentb-site/gentb_website/tb_website/apps/predict/predict_pipeline

on orchestra.
I have changed all paths so they function for testing from an individual account.

We next have to change the paths to the pipeline from the site/supervisord. 

Currently awaiting Raman's input on this.

**Comment by mahafarhat** [comment]
Here is input from Raman:

The path to the pipeline code can be changed through the Django Admin.

There should be a section called: "Pipeline Scripts Directory” that is editable through a web interface.

The model is here:  https://github.com/IQSS/gentb-site/blob/master/apps/predict/models.py#L296

**Comment by doctormo** [comment]
Script location and data files confirmed changed.
