### ISSUE TITLE
Users want the option to flag input data to be deleted as soon as final prediction is generated

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#82]
some users have data (fastq's, vcfs etc) that they cannot share with the public. They would like the comfort of knowing their data has been deleted after prediction ie. csv and json file's have been generated. 

Can we create a dropdown that defaults to not delete Fastq's, but allows for deletion for those that want it?

**Comment by doctormo** [comment]
We could have a "delete source files" checkbox. It'd be an extra step since downloading the source files isn't a part of the pipeline, deleting them shouldn't be either.

**Comment by mahafarhat** [comment]
no need to show data download step, let's just have a a line at the end of the generate matrix python (and part of this step) code that deletes fastq's, sams and vcf's after generating the csv file.

**Comment by doctormo** [comment]
The matrix python doesn't know anything about the downloaded source files, they're tracked from the database. So having the matrix program delete them would cause the django website to be confused and would cause us some problems. As a matter of scope (keeping a program doing it's job) we shouldn't touch files in the pipeline we aren't supposed to output and we certainly shouldn't delete any files that aren't 'ours'.

We can also talk about this some more tomorrow to get the best plan.

**Comment by doctormo** [comment]
This is now available for use.
