### ISSUE TITLE
incorporate a lineage call on the prediction page

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#92]
input will not change, but we need to include some additional code and a small lineage database that acts on one gunzipped fastq file (it could be either one of the two paired files) and will give an output similar to this:

Peru2959_R1     777777777760771 53      777777777760771 43      T1     4

First field is the input file name, second field in the inferred spoligotype, ignore the third field, fourth field is closest spoligotype from the database, fifth field is the number of spacers matched out of 43, and sixth field is the spoligotype family and the last field is the lineage number. 

I know that we have structured the pipeline to have several serial steps, but is it possible for it to run the lineage call in parallel with the resistance prediction, perhaps after the stampy step so they are not both reading the same file.

**Comment by doctormo** [comment]
This is now done.
