### ISSUE TITLE
updates to manual & VCF predict text

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#98]
currently the following list of loci is described under the VCF predict page, this needs to be moved to the Manual predict page.

Also on the predict page the description of VCF prediction: "Minimal genotypic information for accurate resistance predictions are below. Genetic regions are listed in order of decreasing importance. For more detailed list of genetic variants see reference Farhat MR, Sultana R et al. Genetic Determinants of Drug Resistance in Mycobacterium tuberculosis and Their Diagnostic Value. AJRCCM 2016 "

is actually the description of the manual prediction.

VCF prediction description should be: "Create a prediction from a variant call file in VCF format. Get more information about the VCF format here." move the link to 1000 genomes project so its still accessible. 

Manual prediction description should be:"Create a prediction though manual selection of 1 or more mutations from a list. This option involves the shortest processing time but does assume that any non-entered mutations have been tested for and are absent. Minimal genotypic information for accurate resistance predictions are below. Genetic regions are listed in order of decreasing importance. For more detailed list of genetic variants see reference Farhat MR, Sultana R et al. Genetic Determinants of Drug Resistance in Mycobacterium tuberculosis and Their Diagnostic Value. AJRCCM 2016"

Here is the recommended minimum list of resistance loci that should be genotyped for accurate resistanc prediction. 

Drug 	Genes
Isoniazid 	katG, inhA promoter, inhA, embB, iniB, kasA, embAB promoter, and ahpC
Rifampicin 	rpoB
Pyrazinamide 	pncA and pncA promoter
Ethambutol 	embB, iniB, embAB promoter, embAB, and embC
Streptomycin 	rpsL, rrs, gid, and rrs-rrl intergenic region
Ethionamide 	inhA promoter, ethA, and inhA
Kanamycin* 	rrs, tlyA*
Capreomycin 	rrs
Amikacin 	rrs
Fluoroquinolones 	gyrA, gyrB
Para-aminosalicylic acid 	thyA
* Note: Gene eis is a predictor of kanamycin resistance, but data for this gene was not available when the predictive model was built.

**Comment by doctormo** [comment]
Fixed
