### ISSUE TITLE
incorporate Mykrobe as a pre-processing pipeline from bam to matrix

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#99]
We're starting a collaboration with Zam Iqbal.

here is the repository:
https://github.com/iqbal-lab/Mykrobe-predictor

we will use his code to go from bam to a json representation of the mutations, we then need to write some code that can convert this back to a VCF or matrix for intake by the random forest model

**Comment by doctormo** [comment]
What is the task that needs doing?

**Comment by mahafarhat** [comment]
let's start by getting the code and incorporating it as a separate pipeline to run on fastq files. Let's see what the output looks like and think about how to reformat this to allow us to run TBpredict.R on it

**Comment by doctormo** [comment]
This would be a request to orchestra to turn it into a module right?

**Comment by mahafarhat** [comment]
no probably best if we install it ourselves, this is not a general use
software and orchestra is unlikely to install it for us

**Comment by doctormo** [comment]
I've completing this issue based on mykrobe being installed on orchestra, the tests passing and the binary program being available here:

    /www/gentb.hms.harvard.edu/data/bin/Mykrobe-predictor/pythonenv/bin/mykrobe

Please create further issues for the next steps in integrating mykrobe with the pipeline.
